# 说明：
#   - 单进程承载所有订阅；
#   - 支持通过 YAML 配置订阅集合、预热、推送目标与 QMT 连接模式；
#   - 若不修改，可直接用于 scripts/run_with_config.py 的 --config 参数。

qmt:
  mode: none
  token: ''

redis:
  host: 127.0.0.1
  port: 6379
  password: null
  topic: xt:topic:bar

subscription:
  codes: [518880.SH, 513880.SH]
  periods: [1m, 1d]
  mode: close_only
  close_delay_ms: 100
  preload_days: 3

logging:
  level: INFO
  json: false
  file: logs/realtime_bridge.log     # 建议开启文件输出，便于轮转
  rotate:
    enabled: true
    max_bytes: 10485760             # 10MB
    backup_count: 5

health:
  enabled: true
  key_prefix: xt:bridge:health      # 健康上报 Redis Key 前缀
  interval_sec: 5                   # 上报间隔
  ttl_sec: 20                       # 键过期时间（秒）
  instance_tag: bridge-A            # 可选：实例标识（用于区分多实例）
