# 说明：
#   - 单进程承载所有订阅；
#   - 支持通过 YAML 配置订阅集合、预热、推送目标与 QMT 连接模式；
#   - 若不修改，可直接用于 scripts/run_with_config.py 的 --config 参数。

qmt:
  mode: none
  token: ''

redis:
  url: "redis://127.0.0.1:6379/0"  # 优先使用 URL；若提供，会解析为 host/port/password/db
  host: 127.0.0.1                   # 当未提供 url 时使用
  port: 6379
  password: null
  db: 0
  topic: xt:topic:bar

subscription:
  codes: [518880.SH, 513880.SH]
  periods: [1m, 1d]
  mode: close_only
  close_delay_ms: 100
  preload_days: 3

logging:
  level: INFO
  json: false
  file: logs/realtime_bridge.log     # 建议开启文件输出，便于轮转
  rotate:
    enabled: true
    max_bytes: 10485760             # 10MB
    backup_count: 5

health:
  enabled: false
  key_prefix: xt:bridge:health      # 健康上报 Redis Key 前缀
  interval_sec: 5                   # 上报间隔
  ttl_sec: 20                       # 键过期时间（秒）
  instance_tag: bridge-A            # 可选：实例标识（用于区分多实例）

control:
  enabled: true
  channel: xt:ctrl:sub          # 控制通道（订阅/退订/查询）
  ack_prefix: xt:ctrl:ack       # 回执前缀：xt:ctrl:ack:{strategy_id}
  registry_prefix: xt:bridge    # 注册表前缀：subs/strategy/... 基于此前缀
  accept_strategies: []         # 可选白名单（空表示允许任何 strategy_id）
